### PR TITLE
Test reporting (holding off this one for now)

### PR DESCRIPTION
**Pull request by erikbra**
asfd

### CODE REVIEW

**Comment by wokket** [comment]
What are you looking to achieve here mate?  If I can help I will...

**Comment by erikbra** [comment]
I wanted to show all tests in a more user-friendly way, to avoid having to poke around in logs to look at failing tests. There are good tools for importing test output xml files from xUnit and NUnit in Azure devops pipelines, but I can't find anything similar in GitHub actions. So I'm trying different test output formats and different GitHub actions, but no luck so far.

**Comment by erikbra** [comment]
Check out if any of these can solve the task:

* https://github.com/dorny/test-reporter
* https://github.com/zyborg/dotnet-tests-report

**Comment by bptillman** [comment]
> Check out if any of these can solve the task:
> 
>     * https://github.com/dorny/test-reporter
> 
>     * https://github.com/zyborg/dotnet-tests-report

Test-reporter looks pretty good to me, since it could just read the test output xml file, versus dotnet-tests-report which does its own run of the tests, which would make the github action build technically different from a local build or any other build/test run that is done.

**Comment by erikbra** [comment]
Superceded by #154

**Pull request closed without merging**
