### PR TITLE
Table casing

### PR DESCRIPTION
**Pull request by cocytus**
Add option to use lowercase table names.

### CODE REVIEW

**Comment by cocytus** [comment]
Fixes #245

**Comment by erikbra** [comment]
Thanks a lot for your contribution, @cocytus !!
This is of course _one_ way of solving this issue. I'd just like to have your opinion on my comments here https://github.com/erikbra/grate/issues/245#issuecomment-1247301636 before I merge this. I try to be a bit conservative with adding new command-line options, as there are already very many, and if this is really a workaround for a bug(ish), I want to consider other options as well.

What do you think of the suggestion of not enclosing the table names in quotes when creating the grate tables for PostgreSQL? Would that work too?

**Comment by cocytus** [comment]
Hei,

Please take a look at the updated PR code. This "works on my machine" :-) I don't have docker, so only a few of the tests actually works.

**Comment by cocytus** [comment]
About the failed tests: Unsure why that happens? On first glanse it seems unrelated to my PR. I rebased on latest main, hope you can retrigger the workflows.

**Comment by erikbra** [comment]
I'm not sure why the tests fail either, I'll try to run the tests on "main" to see if they fail too

**Comment by erikbra** [comment]
Abandoning this in favor of #256 

REALLY sorry for the long time it has taken me to get around to do the last 20% of this, @cocytus. I didn't mean to disrespect your efforts here, and in addition, refuse to finish my own work doing the same in a different way.

I hope I haven't scared you away from creating PRs to grate (although I respect and understand if I have 🤕 ).

Anyways, the feature should be on its way out in the next grate release. Hope to release it in the next few days.

**Pull request closed without merging**
