### PR TITLE
Closes #142: Reduce console output, esp when folder is missing or empty.

### LINKED ISSUE #142: Minimize console output for folders that are nonexistent or with no new scripts
Since grate will suppress console output for skipped files by default, it would make sense to skip output of the extra dividers and whitespace to trim unnecessary content as well. This will help to eliminate noise when verifying that scripts are detected and run appropriately.

Perhaps showing something like:
```
Looking for scripts in xxxx
--no new scripts--
```

and/or checking for a directory before output to enable simplifying the message to

```
Skipping runAfterFirstUp, xxxx folder does not exist
```

_Original comment posted by @docrinehart in https://github.com/erikbra/grate/issues/140#issuecomment-976111155_

### PR DESCRIPTION
**Pull request by wokket**
First cut at reducing output noise, I'm keen for feedback from those with opinions :)

I've opted to remove the Server Name/Database name from every script run line as it seemed a little unnecessary, but this does break back-compat with RH messages.... but so does this entire PR...

There's a few things I'm personally not super happy with, like adding a log line full of spaces just to effectively `Console.WrinteLine()`, but baby steps.

Let me know if you'd like the LogLevel or content of any of the messages changed.

### CODE REVIEW

**Comment by erikbra** [comment]
I think this looks very good in summary, @wokket! The output could use a general cleanup, but I think that is a separate issue, and shouldn't be handled here :)

If you change the output of the message `No sql run, either an empty folder, or all files run against destination previously.`, I'm good to merge this :)

**Comment by wokket** [comment]
There's always more to do, but hopefully this helps address the original issue.

**Comment by erikbra** [comment]
> I think this looks very good in summary, @wokket! The output could use a general cleanup, but I think that is a separate issue, and shouldn't be handled here :)
> 
> If you change the output of the message `No sql run, either an empty folder, or all files run against destination previously.`, I'm good to merge this :)

Sorry, I wrote something other than I meant here, I meant "Change it to `Information` level"

**Comment by erikbra** [comment]
> There's always more to do, but hopefully this helps address the original issue.

Definitely!

> 
> EDIT: Looks like a false negative in the tests?

Yeps, it was. SqlServer tests fail every once in a blue moon, but works when run again (the server fails to start)

**Comment by erikbra** [comment]
Looks good to me! Let's merge :)

**Pull request merged**
