### PR TITLE
Database already exists exception #167

### PR DESCRIPTION
**Pull request by RachelAmbler**

### CODE REVIEW

**Comment by RachelAmbler** [comment]
There's a different issue at play here.

**Comment by erikbra** [comment]
I don't think this is a bad idea, it would solve the first feature request mentioned here: https://github.com/erikbra/grate/issues/167#issuecomment-1020585560

And, I think naming the option "positively" is nicer than RoundhousE's `--donotcreate`. I think I would prefer that the default is to try to create the database, though, as it has been the default behaviour since the middle ages in RoundhousE, and we try to mimic that as closely as possible, if there aren't good arguments to do otherwise.

Would you be OK with re-opening the PR, and changing the default to "please create the database if it doesn't exist"?

Additionaly, I would really appreciate if you are able to make some tests for this new option. It should be sufficient to test that setting the option is respected/reflected in the config, as we have tests for respecting the config in the migrator here: https://github.com/erikbra/grate/blob/main/grate.unittests/Generic/GenericDatabase.cs

**Comment by RachelAmbler** [comment]
@erikbra so you saying you're wanting to go ahead with the PR, but to ensure that the default is `true` ?

If so I can do that tomorrow.

**Comment by erikbra** [comment]
(sorry for late replies, it's been a lot :) )

Yes, please, that would be great!

**Pull request closed without merging**
